[package]
name = "task"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
clap = { version = "4.5.9", features = ["derive"] }
rusqlite = { version = "0.31.0", features = ["bundled", "chrono"] }
serde = {version = "1.0.204", features = ["derive"] }